### ISSUE TITLE
CORS settings

### ISSUE THREAD

**Issue by Rakkoc** [ismetacar/ertis-auth#6]
Hello,

Does Ertis-auth have a CORS setting? I could not use it with direct access from browser via vuejs or angular. It throw CORS error.

**Comment by ismetacar** [comment]
Hi @Rakkoc,

While developing the Ertis Auth project, it was developed in accordance with microservice standards, http and rest standards. It can be positioned as a microservice in any system.

But CORS is cross-cutting concern. It should be handled on the edge. eg. Gateway.

But If we don't have any chance to change this setup, baking CORS setting into microservices might be acceptable. If there is a development about CORS, it will be a process that will contradict the generic approach of the project.

However, I can recommend that, Ertis Auth is developed with the [Sanic](https://github.com/sanic-org/sanic) framework and there are [extensions](https://sanic.readthedocs.io/en/19.3/sanic/extensions.html) in the Sanic ecosystem about CORS. You can quickly solve this problem with extensions. eg. [Sanic Cors](https://github.com/ashleysommer/sanic-cors)

You can find solution in here. https://pypi.org/project/Sanic-Cors/
